---
- name: Install Docker on slave machine
  hosts: webserver
  tasks:
  - name: Install aptitude and update cache
    apt: name=aptitude state=latest update_cache=yes force-apt_get=yes
  - name: Install required system packages
    apt: name={{ item }}  state=latest update_cache=yes
    loop: [ 'apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip','python-pip','virtualenv','python3-set
uptools']    
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/grg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu boinic stable
      state: present
  - name: Install Docker module for python
    pip: 
      name: docker
  - name: Update apt and install docker-ce 
    apt: update_cache=yes name=docker-ce state=latest            

    
