---
- hosts: webserver
- name: Add Docker apt key.
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    ignore_errors: true
    become: true

- name: Add Docker repository.
     apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: true
      become: true

 - name: Install Docker.
      package:
        name: docker-ce
        state: present
      become: true
