---
- hosts: webserver
  tasks:  
  - name: Install docker-ce
    package:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Create a redis container
    docker_container:
      name: data1
      image: ubuntu
      state: started
      recreate: yes
      exposed_ports:
        - 8080
